### ISSUE TITLE
action metanorma generation is not compiling a PDF, just HMTL

### ISSUE THREAD

**Issue by nilshempelmann** [opengeospatial/climate-resilience-dwg#11]
@gbuehler 
Still a little bug here, since the PDF is not generated.

**Comment by staghavikish** [comment]
@nilshempelmann I noticed in the case of the FMSDI Phase 3 ER that some of the PNG files were causing problems with the PDF compiler. I changed them to JPG (using Automator), and it worked. But I should also mention that in the case of FMSDI, I could not even create the PDF locally. So it might be worth changing the images to JPG and seeing if it works.

**Comment by gbuehler** [comment]
Looks like Guy and Albert have fixed the images.

**Comment by nilshempelmann** [comment]
FIXED. 
The PDF was blocked by the .gitignore
